/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NovaSenhaRouteImport } from './routes/nova-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppMilitaresRouteImport } from './routes/_app.militares'
import { Route as AppItensRouteImport } from './routes/_app.itens'
import { Route as AppFaturasRouteImport } from './routes/_app.faturas'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppComprasRouteImport } from './routes/_app.compras'

const NovaSenhaRoute = NovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMilitaresRoute = AppMilitaresRouteImport.update({
  id: '/militares',
  path: '/militares',
  getParentRoute: () => AppRoute,
} as any)
const AppItensRoute = AppItensRouteImport.update({
  id: '/itens',
  path: '/itens',
  getParentRoute: () => AppRoute,
} as any)
const AppFaturasRoute = AppFaturasRouteImport.update({
  id: '/faturas',
  path: '/faturas',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppComprasRoute = AppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/compras': typeof AppComprasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/faturas': typeof AppFaturasRoute
  '/itens': typeof AppItensRoute
  '/militares': typeof AppMilitaresRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/compras': typeof AppComprasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/faturas': typeof AppFaturasRoute
  '/itens': typeof AppItensRoute
  '/militares': typeof AppMilitaresRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/_app/compras': typeof AppComprasRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/faturas': typeof AppFaturasRoute
  '/_app/itens': typeof AppItensRoute
  '/_app/militares': typeof AppMilitaresRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/nova-senha'
    | '/compras'
    | '/configuracoes'
    | '/faturas'
    | '/itens'
    | '/militares'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/nova-senha'
    | '/compras'
    | '/configuracoes'
    | '/faturas'
    | '/itens'
    | '/militares'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/nova-senha'
    | '/_app/compras'
    | '/_app/configuracoes'
    | '/_app/faturas'
    | '/_app/itens'
    | '/_app/militares'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  NovaSenhaRoute: typeof NovaSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nova-senha': {
      id: '/nova-senha'
      path: '/nova-senha'
      fullPath: '/nova-senha'
      preLoaderRoute: typeof NovaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/militares': {
      id: '/_app/militares'
      path: '/militares'
      fullPath: '/militares'
      preLoaderRoute: typeof AppMilitaresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/itens': {
      id: '/_app/itens'
      path: '/itens'
      fullPath: '/itens'
      preLoaderRoute: typeof AppItensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/faturas': {
      id: '/_app/faturas'
      path: '/faturas'
      fullPath: '/faturas'
      preLoaderRoute: typeof AppFaturasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compras': {
      id: '/_app/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AppComprasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppComprasRoute: typeof AppComprasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppFaturasRoute: typeof AppFaturasRoute
  AppItensRoute: typeof AppItensRoute
  AppMilitaresRoute: typeof AppMilitaresRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppComprasRoute: AppComprasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppFaturasRoute: AppFaturasRoute,
  AppItensRoute: AppItensRoute,
  AppMilitaresRoute: AppMilitaresRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  NovaSenhaRoute: NovaSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
